/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/JAjJGtn6I5I
 */
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { CardContent, CardFooter, Card } from "@/components/ui/card";

export function AddCourse() {
  return (
    <div className="mx-auto w-full px-4 lg:px-6">
      <div className="grid gap-6">
        <div className="space-y-6 lg:col-span-2 xl:col-span-3">
          <div className="flex items-center space-x-4">
            <h1 className="text-3xl font-bold">Cursos</h1>
            <Button size="sm">Agregar Curso</Button>
          </div>
          <div className="grid w-full gap-4">
            <div className="flex items-center p-4 rounded-lg bg-gray-100 dark:bg-gray-800">
              <Link className="flex-1" href="#">
                <div className="font-semibold">PreKinder</div>
                <div className="text-sm text-gray-500 dark:text-gray-400">
                  Instructor: Maria Camila Yevenes
                </div>
              </Link>
              <div>
                <div>Ver</div>
                <div>Evaluar</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function MoreHorizontalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="1" />
      <circle cx="19" cy="12" r="1" />
      <circle cx="5" cy="12" r="1" />
    </svg>
  );
}
